#!/usr/bin/env python3
"""madrascheck-dev 전체 저장소를 재서 로컬 전용 등급표를 만든다.

비공개 저장소명과 결과는 .internal/ 및 사용자 캐시에만 쓴다. 공개 소스나 배포
산출물에는 포함하지 않는다. 원본 작업 디렉터리를 건드리지 않고 얕은 캐시 복제본을
사용하며, 같은 커밋은 이전 결과를 재사용한다.
"""

from concurrent.futures import ThreadPoolExecutor, as_completed
import argparse
import datetime as dt
import hashlib
import html
import json
import os
from pathlib import Path
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parent.parent
ORG = "madrascheck-dev"
LOCAL_OUT = ROOT / ".internal"
CACHE = Path(os.environ.get(
    "FIXEARLY_INTERNAL_CACHE",
    str(Path.home() / ".cache" / "fixearly-internal" / ORG),
)).expanduser().resolve()
CLONES = CACHE / "clones"
WORK = CACHE / "work"
RESULTS = CACHE / "results"
SCORING_VERSION = "v14"
JS_LANGS = {"JavaScript", "TypeScript"}
MIN_REPRESENTATIVE_COVERAGE_PCT = 10.0

# 물리 LOC와 분석 커버리지를 셀 때 코드로 보는 확장자. JSON/YAML/XML/문서는 빼고,
# 실행 코드·템플릿·스타일·SQL처럼 제품 동작을 만드는 추적 소스만 센다.
SOURCE_LANGUAGES = {
    ".js": "JavaScript", ".jsx": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TypeScript", ".mts": "TypeScript", ".cts": "TypeScript",
    ".java": "Java", ".jsp": "JSP", ".jspx": "JSP",
    ".py": "Python", ".go": "Go", ".rs": "Rust",
    ".kt": "Kotlin", ".kts": "Kotlin", ".scala": "Scala", ".groovy": "Groovy",
    ".swift": "Swift", ".dart": "Dart", ".rb": "Ruby", ".php": "PHP",
    ".c": "C", ".h": "C/C++", ".cc": "C/C++", ".cpp": "C/C++", ".cxx": "C/C++",
    ".hpp": "C/C++", ".cs": "C#", ".m": "Objective-C", ".mm": "Objective-C",
    ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell", ".lua": "Lua", ".r": "R",
    ".vue": "Vue", ".svelte": "Svelte",
    ".html": "HTML", ".htm": "HTML", ".css": "CSS", ".scss": "CSS",
    ".sass": "CSS", ".less": "CSS", ".sql": "SQL",
}
NON_PRODUCT_PARTS = {
    "node_modules", "compiled", "vendor", "vendored", "third-party", "third_party", "thirdparty",
    "generated", "codegen", ".generated", "dist", "build", "coverage",
    "example", "examples", "sample", "samples", "demo", "demos", "playground",
    "sandbox", "website", "scripts", "tmp", "docs", "fixtures", "mocks",
    "__fixtures__", "__mocks__", "__snapshots__", "benchmark", "benchmarks",
}
TEST_PARTS = {"test", "tests", "__test__", "__tests__", "e2e", "spec"}
GENERATED_BANNER_RE = re.compile(
    r"@generated\b|code generated .*do not edit|generated by .*do not edit|"
    r"auto(?:matically)?[- ]generated(?: file| by)?|"
    r"this file (?:is )?generated|do not edit(?: this file)?|손수정\s*금지|"
    r"자동\s*생성.{0,80}(?:수정\s*금지|손수정)", re.I | re.S,
)
GENERATED_NAME_RE = re.compile(
    r"(^|/)(generated|codegen)\.[cm]?[jt]sx?$|(^|/)[^/]+\.(generated|codegen)\.[cm]?[jt]sx?$",
    re.I,
)
TEST_NAME_RE = re.compile(r"\.(test|spec|test-d|bench|benchmark|stories|e2e)\.[^.]+$", re.I)

# 자동 판별로는 근거가 부족한 저장소별 측정 범위. 단순히 점수를 올리려고 빼지 않고,
# 배포 소스가 아닌 복제 번들·개발 샘플임을 경로와 저장소 구조로 확인한 것만 적는다.
INTERNAL_SCOPES = {
    "flow-was": {
        "exclude": [
            "src/WEB-INF/src/jex/studio",
            "src/flow-renewal/module/lib",
            "src/flow-renewal/js/lib",
            "src/js/lib",
            "src/js/jquery-ui.js",
            "src/js/jquery.datepicker",
            "src/js/jquery.js",
            "src/js/admin/assets/js/vue.js",
            "src/update-note/data",
            "flow-library/flow-task-util/src/gridSample.js",
            "flow-library/flow-task-util/src/gridSampleMoblie.js",
        ],
        "note": "Jex Studio 생성 DTO·읽기 가능한 벤더 번들·업데이트 데이터·grid 샘플 제외",
    },
    "flow-library": {
        "exclude": ["flow-kit-dev"],
        "note": "배포 packages와 분리된 개발·샘플 작업공간 제외",
    },
}


def run(args, *, cwd=None, timeout=600):
    return subprocess.run(
        [str(x) for x in args], cwd=cwd, capture_output=True, text=True,
        timeout=timeout, env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
    )


def gh_json(args, timeout=120):
    proc = run(["gh", *args], timeout=timeout)
    if proc.returncode:
        raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or "GitHub 조회 실패")
    return json.loads(proc.stdout)


def repositories():
    return gh_json([
        "repo", "list", ORG, "--limit", "200", "--json",
        "name,nameWithOwner,visibility,isArchived,isFork,defaultBranchRef,url,updatedAt,primaryLanguage",
    ])


def languages(slug):
    return gh_json(["api", f"repos/{slug}/languages"])


def cached_row(path, sha):
    if not path.exists():
        return None
    try:
        row = json.loads(path.read_text(encoding="utf-8"))
        if (row.get("sha") == sha and row.get("scoringVersion") == SCORING_VERSION
                and row.get("measurementKey") == measurement_key(row.get("name", ""))):
            return row
    except Exception:
        return None
    return None


def measurement_key(repo_name):
    """엔진 코드나 저장소별 범위가 바뀌면 같은 SHA의 낡은 측정을 재사용하지 않는다."""
    engine = (ROOT / "bin" / "fixearly.mjs").read_bytes()
    scanner = Path(__file__).read_bytes()
    scope = json.dumps(
        INTERNAL_SCOPES.get(repo_name, {}), ensure_ascii=False, sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(engine + b"\0" + scanner + b"\0" + scope).hexdigest()[:16]


def scope_excluded(repo_name, rel_path):
    for pattern in INTERNAL_SCOPES.get(repo_name, {}).get("exclude", []):
        regex = re.escape(pattern).replace(r"\*", "[^/]*")
        if re.search(regex, rel_path):
            return True
    return False


def source_inventory(repo_name, repo_dir):
    """추적된 제품 소스의 물리 LOC와 언어 구성을 센다."""
    tracked = run(["git", "-C", repo_dir, "ls-files", "-z"], timeout=120)
    if tracked.returncode:
        return {"totalPhysicalLines": 0, "sourceFiles": 0, "languageLines": {}}

    language_lines = {}
    source_files = 0
    total_lines = 0
    for rel_path in tracked.stdout.split("\0"):
        if not rel_path:
            continue
        normalized = rel_path.replace("\\", "/")
        suffix = Path(normalized).suffix.lower()
        language = SOURCE_LANGUAGES.get(suffix)
        if not language:
            continue
        lowered = normalized.lower()
        parts = set(lowered.split("/"))
        if (parts & NON_PRODUCT_PARTS or parts & TEST_PARTS or TEST_NAME_RE.search(lowered)
                or lowered.endswith(".d.ts") or GENERATED_NAME_RE.search(lowered)
                or scope_excluded(repo_name, normalized)):
            continue
        try:
            text = (repo_dir / rel_path).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if GENERATED_BANNER_RE.search(text[:2400]):
            continue
        if language == "JavaScript" and len(text) >= 500:
            lines = text.split("\n")
            longest = max((len(line) for line in lines), default=0)
            if re.search(r"\.(min|bundle)\.[cm]?js$", lowered) or longest > 2000 or len(text) / len(lines) > 200:
                continue
        physical_lines = text.count("\n") + (1 if text else 0)
        source_files += 1
        total_lines += physical_lines
        language_lines[language] = language_lines.get(language, 0) + physical_lines

    language_lines = dict(sorted(language_lines.items(), key=lambda item: (-item[1], item[0])))
    return {
        "totalPhysicalLines": total_lines,
        "sourceFiles": source_files,
        "languageLines": language_lines,
    }


def grade_is_representative(analyzed_physical_lines, total_physical_lines):
    """JS/TS 조각의 점수를 저장소 등급으로 표시해도 될 만큼 범위가 넓은지 본다."""
    if not total_physical_lines:
        return False
    return analyzed_physical_lines / total_physical_lines * 100 >= MIN_REPRESENTATIVE_COVERAGE_PCT


def repo_sha(repo_dir):
    proc = run(["git", "-C", repo_dir, "rev-parse", "HEAD"])
    return proc.stdout.strip() if proc.returncode == 0 else ""


def prepare_clone(repo):
    slug, name = repo["nameWithOwner"], repo["name"]
    branch = (repo.get("defaultBranchRef") or {}).get("name")
    if not branch:
        return None, "기본 브랜치 없음"
    dst = CLONES / name
    if (dst / ".git").is_dir():
        fetch = run(["git", "-C", dst, "fetch", "--depth", "1", "origin", branch], timeout=300)
        if fetch.returncode:
            return None, fetch.stderr.strip() or "fetch 실패"
        checkout = run(["git", "-C", dst, "checkout", "--detach", "-f", "FETCH_HEAD"], timeout=120)
        if checkout.returncode:
            return None, checkout.stderr.strip() or "checkout 실패"
        return dst, None

    args = [
        "gh", "repo", "clone", slug, dst, "--", "--depth", "1",
        "--filter=blob:none", "--single-branch", "--branch", branch,
    ]
    local_reference = Path.home() / "dev" / ORG / name
    if (local_reference / ".git").is_dir():
        args.extend(["--reference-if-able", local_reference])
    clone = run(args, timeout=600)
    if clone.returncode or not (dst / ".git").is_dir():
        return None, clone.stderr.strip() or clone.stdout.strip() or "clone 실패"
    return dst, None


def base_row(repo, language_bytes):
    branch = (repo.get("defaultBranchRef") or {}).get("name")
    primary = (repo.get("primaryLanguage") or {}).get("name")
    scope = INTERNAL_SCOPES.get(repo["name"], {})
    return {
        "repo": repo["nameWithOwner"],
        "name": repo["name"],
        "url": repo["url"],
        "visibility": repo["visibility"],
        "branch": branch,
        "updatedAt": repo["updatedAt"],
        "primaryLanguage": primary,
        "jsTsBytes": sum(language_bytes.get(lang, 0) for lang in JS_LANGS),
        "archived": repo["isArchived"],
        "fork": repo["isFork"],
        "scoringVersion": SCORING_VERSION,
        "measurementKey": measurement_key(repo["name"]),
        "scopeAdjusted": bool(scope),
        "scopeNote": scope.get("note"),
    }


def measure(repo, language_bytes):
    row = base_row(repo, language_bytes)
    if not row["branch"]:
        return {**row, "status": "na", "reason": "빈 저장소"}

    repo_dir, error = prepare_clone(repo)
    if error:
        return {**row, "status": "error", "reason": error[:300]}
    sha = repo_sha(repo_dir)
    saved = cached_row(RESULTS / f"{repo['name']}.json", sha)
    if saved:
        return {**saved, **row, "cached": True}

    inventory = source_inventory(repo["name"], repo_dir)
    row = {**row, **inventory, "sha": sha}
    if row["jsTsBytes"] <= 0:
        empty = {
            **row, "status": "na", "cached": False, "reason": "JS/TS 정밀분석 범위 없음",
            "analyzedPhysicalLines": 0, "coveragePct": 0,
        }
        (RESULTS / f"{repo['name']}.json").write_text(
            json.dumps(empty, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        return empty

    work = WORK / repo["name"]
    out = work / "out"
    work.mkdir(parents=True, exist_ok=True)
    out.mkdir(parents=True, exist_ok=True)
    command = [
        "node", ROOT / "bin" / "fixearly.mjs", f"--dir={repo_dir}", f"--out={out}",
    ]
    excludes = INTERNAL_SCOPES.get(repo["name"], {}).get("exclude", [])
    if excludes:
        command.append(f"--exclude={','.join(excludes)}")
    proc = run(command, cwd=work, timeout=1200)
    result_file = out / "fixearly.json"
    if proc.returncode or not result_file.exists():
        message = proc.stderr.strip() or proc.stdout.strip().splitlines()[-1:] or ["분석 실패"]
        if isinstance(message, list):
            message = message[0]
        if "파일을 찾을 수 없습니다" in message or "소스 파일이 없습니다" in message:
            return {
                **row, "status": "na", "reason": "분석 가능한 JS/TS 소스 없음",
                "analyzedPhysicalLines": 0, "coveragePct": 0,
            }
        return {**row, "status": "error", "reason": str(message)[:300]}

    stats = json.loads(result_file.read_text(encoding="utf-8"))
    quality, source = stats["quality"], stats["source"]
    if source["files"] <= 0 or source["codeLines"] <= 0:
        empty = {
            **row, "status": "na", "cached": False, "reason": "분석 가능한 JS/TS 소스 없음",
            "analyzedPhysicalLines": 0, "coveragePct": 0,
        }
        (RESULTS / f"{repo['name']}.json").write_text(
            json.dumps(empty, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        return empty
    analyzed_physical = source["totalLines"]
    coverage = round(analyzed_physical / inventory["totalPhysicalLines"] * 100, 1) \
        if inventory["totalPhysicalLines"] else 0
    representative = grade_is_representative(
        analyzed_physical, inventory["totalPhysicalLines"],
    )
    measured = {
        **row,
        "sha": sha,
        "status": "ok" if representative else "partial",
        "cached": False,
        "files": source["files"],
        "codeLines": source["codeLines"],
        "analyzedPhysicalLines": analyzed_physical,
        "coveragePct": min(100, coverage),
        "cognitiveAvg": quality["cognitive"]["avg"],
        "cognitiveMax": quality["cognitive"]["max"],
        "duplication": quality["duplication"]["percent"],
        "avgFileLines": quality["avgFileLines"],
        "quadratic": quality["quadratic"]["candidates"],
        "seqIo": quality["seqIo"]["sites"],
        "generatedAt": stats["generatedAt"],
    }
    if representative:
        measured.update({
            "grade": quality["grade"],
            "gradeBase": quality["gradeBase"],
            "score": quality["score"],
        })
    else:
        # 작은 이종언어 조각의 점수가 정식 저장소 등급으로 재사용되지 않도록 격리한다.
        measured.update({
            "sliceGrade": quality["grade"],
            "sliceGradeBase": quality["gradeBase"],
            "sliceScore": quality["score"],
        })
        measured["reason"] = (
            f"JS/TS 분석률 {coverage:.2f}% — "
            f"{MIN_REPRESENTATIVE_COVERAGE_PCT:g}% 미만이라 저장소 대표성 부족"
        )
    (RESULTS / f"{repo['name']}.json").write_text(
        json.dumps(measured, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return measured


def dashboard_html(payload):
    safe_json = json.dumps(payload, ensure_ascii=False).replace("<", "\\u003c")
    return f'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>madrascheck-dev · fixearly internal</title>
<style>
:root{{--paper:#f6f8fb;--card:#fff;--line:#e2e8f0;--ink:#111827;--muted:#64748b;--accent:#2563eb;
--S:#0f7a63;--A:#2f8f5b;--B:#7d8a2c;--C:#c0862e;--D:#bf4a38;--E:#8f2f24}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"Apple SD Gothic Neo",sans-serif}}
.wrap{{max-width:1800px;margin:auto;padding:28px clamp(16px,3vw,40px) 60px}}a{{color:inherit;text-decoration:none}}
.top{{display:flex;gap:18px;align-items:flex-start;justify-content:space-between;flex-wrap:wrap}}h1{{font-size:26px;margin:0;letter-spacing:-.03em}}
.sub{{color:var(--muted);margin:5px 0 0}}.back{{border:1px solid var(--line);background:var(--card);padding:8px 12px;border-radius:9px;color:var(--muted)}}
.summary{{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:10px;margin:24px 0}}
.stat{{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px 16px}}.stat small{{display:block;color:var(--muted)}}.stat b{{font-size:22px}}
.controls{{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:12px}}input{{flex:1;min-width:220px;border:1px solid var(--line);border-radius:10px;padding:10px 12px;background:#fff}}.filterset{{display:flex;align-items:center;gap:6px}}.filterset>small{{color:var(--muted);font-size:10px;font-weight:700;letter-spacing:.06em}}
.filters{{display:flex;gap:5px;flex-wrap:wrap}}button{{border:1px solid var(--line);background:#fff;color:var(--muted);border-radius:8px;padding:8px 10px;cursor:pointer}}button.on{{background:var(--ink);color:#fff;border-color:var(--ink)}}
.table{{overflow:auto;background:#fff;border:1px solid var(--line);border-radius:12px}}table{{width:100%;border-collapse:collapse;min-width:1560px}}th,td{{padding:10px 12px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}}th{{position:sticky;top:0;background:#f8fafc;color:var(--muted);font-size:11px;letter-spacing:.04em;cursor:pointer;z-index:1}}th:first-child,td:first-child{{text-align:left;position:sticky;left:0;background:inherit}}tbody tr{{background:#fff}}tbody tr:hover{{background:#f8fbff}}td:first-child{{font-weight:650}}.meta{{display:block;color:var(--muted);font-size:10.5px;font-weight:400}}
.grade{{display:inline-grid;place-items:center;min-width:38px;padding:3px 7px;border-radius:6px;color:white;font-weight:800}}.gS{{background:var(--S)}}.gA{{background:var(--A)}}.gB{{background:var(--B)}}.gC{{background:var(--C)}}.gD{{background:var(--D)}}.gE{{background:var(--E)}}.gNA{{background:#94a3b8}}
.weight{{display:inline-grid;place-items:center;min-width:48px;padding:3px 7px;border-radius:999px;font-size:11px;font-weight:750}}.wheavy{{background:#f3e8ff;color:#6b21a8}}.wmiddle{{background:#e0e7ff;color:#3730a3}}.wwelter{{background:#dbeafe;color:#1d4ed8}}.wlight{{background:#dcfce7;color:#166534}}.wfly{{background:#fef3c7;color:#92400e}}.wstraw{{background:#f1f5f9;color:#475569}}
.score{{font-size:16px;font-weight:800}}.na{{color:var(--muted);text-align:left!important}}.foot{{color:var(--muted);font-size:12px;margin-top:12px}}
.cov{{display:flex;align-items:center;justify-content:flex-end;gap:7px;min-width:105px}}.cov span{{font-variant-numeric:tabular-nums;font-weight:700;min-width:42px}}.cov i{{width:48px;height:5px;background:#e2e8f0;border-radius:9px;overflow:hidden}}.cov b{{display:block;height:100%;background:var(--accent);border-radius:inherit}}
.langmix{{width:190px}}.langbar{{display:flex;width:100%;height:7px;border-radius:8px;overflow:hidden;background:#e2e8f0}}.langbar i{{display:block;height:100%;min-width:1px}}.langlabels{{display:flex;gap:7px;margin-top:4px;color:var(--muted);font-size:10.5px}}.langlabels span{{display:inline-flex;align-items:center;gap:3px}}.langlabels b{{width:6px;height:6px;border-radius:2px}}
@media(max-width:900px){{.summary{{grid-template-columns:repeat(2,1fr)}}h1{{font-size:22px}}}}
</style></head><body><main class="wrap">
<div class="top"><div><h1>madrascheck-dev · 전체 등급</h1><p class="sub">비공개 로컬 뷰 · 모든 언어의 소스 규모 + JS/TS 품질 분석 · fixearly {html.escape(SCORING_VERSION)}</p></div><a class="back" href="../">← 공개 랜딩</a></div>
<section class="summary" id="summary"></section>
<div class="controls"><input id="q" type="search" placeholder="저장소 검색" aria-label="저장소 검색"><div class="filterset"><small>체급</small><div class="filters" id="weights"></div></div><div class="filterset"><small>등급</small><div class="filters" id="filters"></div></div></div>
<div class="table"><table><thead><tr>
<th data-key="name">저장소</th><th data-key="totalPhysicalLines">체급</th><th data-key="grade">JS/TS 등급</th><th data-key="score">점수</th><th data-key="coveragePct">JS/TS 분석률</th><th data-key="codeLines">JS/TS 코드 줄</th><th data-key="totalPhysicalLines">전체 소스 줄</th><th>언어 비율</th><th data-key="files">분석 파일</th><th data-key="cognitiveAvg">인지 평균</th><th data-key="cognitiveMax">인지 최대</th><th data-key="duplication">중복 %</th><th data-key="avgFileLines">파일 평균</th><th data-key="quadratic">O(n²)</th><th data-key="seqIo">순차 I/O</th><th data-key="updatedAt">저장소 갱신</th>
</tr></thead><tbody id="rows"></tbody></table></div>
<p class="foot"><b>JS/TS 분석률</b>은 전체 소스 줄 가운데 fixearly가 품질을 읽은 JS/TS 줄의 비율이다. 100%에 가까울수록 등급이 저장소 전체를 더 잘 대표하며, <b>{MIN_REPRESENTATIVE_COVERAGE_PCT:g}% 미만은 대표성 부족으로 N/A</b> 처리한다. 체급은 전체 소스 줄 기준: 스트로 &lt;5k · 플라이 5–15k · 라이트 15–30k · 웰터 30–60k · 미들 60–120k · 헤비 120k+. 생성 {html.escape(payload['generatedAt'])}</p>
</main><script>
const DATA={safe_json};let filter='ALL',weightFilter='ALL',sortKey='score',dir=1;
const rows=DATA.rows, ok=rows.filter(x=>x.status==='ok'), na=rows.length-ok.length;
const avg=ok.length?Math.round(ok.reduce((a,x)=>a+x.score,0)/ok.length):0;
const totalPhysical=rows.reduce((a,x)=>a+(x.totalPhysicalLines||0),0), analyzedPhysical=rows.reduce((a,x)=>a+(x.analyzedPhysicalLines||0),0);
const totalCoverage=totalPhysical?Math.round(analyzedPhysical/totalPhysical*1000)/10:0;
const dist={{}};for(const x of ok)dist[x.gradeBase]=(dist[x.gradeBase]||0)+1;
const compact=n=>new Intl.NumberFormat('ko-KR',{{notation:'compact',maximumFractionDigits:1}}).format(n||0);
const WEIGHTS=[{{k:'heavy',ko:'헤비',range:'120k+',lo:120000,hi:Infinity}},{{k:'middle',ko:'미들',range:'60–120k',lo:60000,hi:120000}},{{k:'welter',ko:'웰터',range:'30–60k',lo:30000,hi:60000}},{{k:'light',ko:'라이트',range:'15–30k',lo:15000,hi:30000}},{{k:'fly',ko:'플라이',range:'5–15k',lo:5000,hi:15000}},{{k:'straw',ko:'스트로',range:'<5k',lo:1,hi:5000}}];
const weightOf=n=>WEIGHTS.find(w=>(Number(n)||0)>=w.lo&&(Number(n)||0)<w.hi)||null;
const weightCount={{}};for(const x of rows){{const w=weightOf(x.totalPhysicalLines);if(w)weightCount[w.k]=(weightCount[w.k]||0)+1}}
document.getElementById('summary').innerHTML=[['저장소',rows.length],['헤비급',weightCount.heavy||0],['JS/TS 측정',ok.length],['전체 소스',compact(totalPhysical)+'줄'],['JS/TS 분석률',totalCoverage+'%'],['평균 점수',avg]].map(x=>`<div class="stat"><small>${{x[0]}}</small><b>${{x[1]}}</b></div>`).join('');
const grades=['ALL','S','A','B','C','D','E','N/A'];
document.getElementById('filters').innerHTML=grades.map(g=>`<button data-g="${{g}}" class="${{g==='ALL'?'on':''}}">${{g}}${{dist[g]?` ${{dist[g]}}`:g==='N/A'?` ${{na}}`:''}}</button>`).join('');
document.getElementById('weights').innerHTML=[{{k:'ALL',ko:'전체'}},...WEIGHTS].map(w=>`<button data-w="${{w.k}}" class="${{w.k==='ALL'?'on':''}}" title="${{w.range||'모든 체급'}}">${{w.ko}}${{weightCount[w.k]?` ${{weightCount[w.k]}}`:''}}</button>`).join('');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
const fmt=n=>n==null?'—':Number(n).toLocaleString();
const cov=x=>{{const p=Math.max(0,Math.min(100,Number(x.coveragePct)||0));return `<div class="cov"><span>${{p.toFixed(1)}}%</span><i><b style="width:${{p}}%"></b></i></div>`}};
const LANG={{TypeScript:['TS','#3178c6'],JavaScript:['JS','#e0b400'],Java:['Java','#b07219'],JSP:['JSP','#e76f51'],Swift:['Swift','#f05138'],'Objective-C':['Obj-C','#438eff'],'C/C++':['C++','#659ad2'],C:['C','#555'],Python:['Py','#3572a5'],Kotlin:['Kt','#a97bff'],Dart:['Dart','#00b4ab'],CSS:['CSS','#8b5cf6'],HTML:['HTML','#e34c26'],SQL:['SQL','#2a9d8f'],Vue:['Vue','#41b883'],Svelte:['Svelte','#ff3e00'],Shell:['Sh','#64748b'],Other:['기타','#94a3b8']}};
const langData=x=>{{const all=Object.entries(x.languageLines||{{}}),total=x.totalPhysicalLines||0;if(!total||!all.length)return[];const top=all.slice(0,5).map(([name,lines])=>({{name,lines}})),rest=all.slice(5).reduce((a,[,lines])=>a+lines,0);if(rest)top.push({{name:'Other',lines:rest}});return top.map(v=>{{const style=LANG[v.name]||[v.name,'#94a3b8'];return{{...v,abbr:style[0],color:style[1],pct:v.lines/total*100}}}})}};
const langCell=x=>{{const data=langData(x);if(!data.length)return'—';const label=data.map(v=>`${{v.abbr}} ${{v.pct.toFixed(1)}}%`).join(' · ');const bars=data.map(v=>`<i style="width:${{v.pct}}%;background:${{v.color}}"></i>`).join('');const labels=data.slice(0,3).map(v=>`<span><b style="background:${{v.color}}"></b>${{esc(v.abbr)}} ${{Math.round(v.pct)}}%</span>`).join('');return`<div class="langmix" title="${{esc(label)}}"><div class="langbar" role="img" aria-label="${{esc(label)}}">${{bars}}</div><div class="langlabels">${{labels}}</div></div>`}};
const weightBadge=x=>{{const w=weightOf(x.totalPhysicalLines);return w?`<span class="weight w${{w.k}}" title="${{w.range}}">${{w.ko}}</span>`:'—'}};
function render(){{const q=document.getElementById('q').value.toLowerCase();let list=rows.filter(x=>(!q||x.repo.toLowerCase().includes(q))&&(filter==='ALL'||(filter==='N/A'?x.status!=='ok':x.gradeBase===filter))&&(weightFilter==='ALL'||weightOf(x.totalPhysicalLines)?.k===weightFilter));
list.sort((a,b)=>{{let x=a[sortKey],y=b[sortKey];if(x==null)x=sortKey==='score'?999999:'';if(y==null)y=sortKey==='score'?999999:'';return (typeof x==='number'?x-y:String(x).localeCompare(String(y)))*dir}});
document.getElementById('rows').innerHTML=list.map(x=>{{const scope=x.scopeAdjusted?` · scope: ${{esc(x.scopeNote)}}`:'';const meta=`${{esc(x.primaryLanguage||'—')}} · ${{esc(x.branch||'—')}}${{x.sha?` · ${{esc(x.sha.slice(0,7))}}`:''}}${{scope}}`;if(x.status!=='ok')return `<tr><td><a href="${{esc(x.url)}}" target="_blank">${{esc(x.name)}}</a><span class="meta">${{meta}} · ${{esc(x.reason)}}</span></td><td>${{weightBadge(x)}}</td><td><span class="grade gNA">N/A</span></td><td>—</td><td>${{cov(x)}}</td><td>${{fmt(x.codeLines||0)}}</td><td>${{fmt(x.totalPhysicalLines)}}</td><td>${{langCell(x)}}</td><td>${{x.files==null?'—':fmt(x.files)}}</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>${{(x.updatedAt||'').slice(0,10)}}</td></tr>`;return `<tr><td><a href="${{esc(x.url)}}" target="_blank">${{esc(x.name)}}</a><span class="meta">${{meta}}</span></td><td>${{weightBadge(x)}}</td><td><span class="grade g${{esc(x.gradeBase)}}">${{esc(x.grade)}}</span></td><td class="score">${{x.score}}</td><td>${{cov(x)}}</td><td>${{fmt(x.codeLines)}}</td><td>${{fmt(x.totalPhysicalLines)}}</td><td>${{langCell(x)}}</td><td>${{fmt(x.files)}}</td><td>${{fmt(x.cognitiveAvg)}}</td><td>${{fmt(x.cognitiveMax)}}</td><td>${{fmt(x.duplication)}}</td><td>${{fmt(x.avgFileLines)}}</td><td>${{fmt(x.quadratic)}}</td><td>${{fmt(x.seqIo)}}</td><td>${{(x.updatedAt||'').slice(0,10)}}</td></tr>`}}).join('')}}
document.getElementById('q').addEventListener('input',render);document.getElementById('filters').addEventListener('click',e=>{{const b=e.target.closest('button');if(!b)return;filter=b.dataset.g;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('on',x===b));render()}});document.getElementById('weights').addEventListener('click',e=>{{const b=e.target.closest('button');if(!b)return;weightFilter=b.dataset.w;document.querySelectorAll('#weights button').forEach(x=>x.classList.toggle('on',x===b));render()}});
document.querySelector('thead').addEventListener('click',e=>{{const k=e.target.dataset.key;if(!k)return;if(sortKey===k)dir*=-1;else{{sortKey=k;dir=k==='name'?1:-1}}render()}});render();
</script></body></html>'''


def write_dashboard(rows):
    payload = {
        "generatedAt": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "organization": ORG,
        "scoringVersion": SCORING_VERSION,
        "rows": sorted(rows, key=lambda row: row["name"].lower()),
    }
    LOCAL_OUT.mkdir(parents=True, exist_ok=True)
    (LOCAL_OUT / "madrascheck.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (LOCAL_OUT / "madrascheck.html").write_text(dashboard_html(payload), encoding="utf-8")
    return payload


def scan(jobs):
    for directory in (CLONES, WORK, RESULTS, LOCAL_OUT):
        directory.mkdir(parents=True, exist_ok=True)
    repos = repositories()
    print(f"{ORG} 저장소 {len(repos)}개 확인", flush=True)

    language_map = {}
    with ThreadPoolExecutor(max_workers=min(8, jobs * 2)) as pool:
        futures = {pool.submit(languages, repo["nameWithOwner"]): repo for repo in repos}
        for future in as_completed(futures):
            repo = futures[future]
            try:
                language_map[repo["nameWithOwner"]] = future.result()
            except Exception as error:
                language_map[repo["nameWithOwner"]] = {}
                print(f"  ! {repo['name']}: 언어 조회 실패 — {error}", flush=True)

    rows = []
    completed = 0
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        futures = {
            pool.submit(measure, repo, language_map.get(repo["nameWithOwner"], {})): repo
            for repo in repos
        }
        for future in as_completed(futures):
            repo = futures[future]
            try:
                row = future.result()
            except Exception as error:
                row = {**base_row(repo, language_map.get(repo["nameWithOwner"], {})),
                       "status": "error", "reason": str(error)[:300]}
            rows.append(row)
            completed += 1
            label = f"{row.get('grade', 'N/A')} {row.get('score', '')}".strip() if row["status"] == "ok" else f"N/A · {row.get('reason', '')}"
            cache = " · cache" if row.get("cached") else ""
            print(f"  [{completed:02d}/{len(repos)}] {repo['name']}: {label}{cache}", flush=True)

    payload = write_dashboard(rows)
    measured = sum(row["status"] == "ok" for row in rows)
    print(f"\n완료: 측정 {measured} · N/A/오류 {len(rows)-measured}", flush=True)
    print(f"대시보드: http://localhost:4173/.internal/madrascheck.html", flush=True)
    return payload


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scan", action="store_true", help="GitHub 저장소를 갱신하고 다시 측정")
    parser.add_argument("--serve", action="store_true", help="생성 뒤 localhost:4173 서버 실행")
    parser.add_argument("--jobs", type=int, default=2, help="동시 측정 수 (기본 2)")
    args = parser.parse_args()

    if args.scan or not (LOCAL_OUT / "madrascheck.html").exists():
        scan(max(1, min(args.jobs, 4)))
    if args.serve:
        os.chdir(ROOT)
        os.execvp(sys.executable, [sys.executable, "-m", "http.server", "4173"])


if __name__ == "__main__":
    main()
