#!/usr/bin/env python3
"""내부 대시보드의 다언어 LOC 범위 회귀 테스트."""

import importlib.util
from pathlib import Path
import subprocess
import tempfile
import unittest


ROOT = Path(__file__).resolve().parent.parent
SPEC = importlib.util.spec_from_file_location(
    "internal_dashboard", ROOT / "tools" / "internal-dashboard.py",
)
dashboard = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(dashboard)


class SourceInventoryTest(unittest.TestCase):
    def test_counts_product_languages_and_excludes_noise(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            subprocess.run(["git", "init", "-q", repo], check=True)
            files = {
                "src/app.ts": "const a = 1;\nconst b = 2;\nexport { a, b };",
                "src/Main.java": "class Main {\n  int x;\n  int y;\n}",
                "src/view.jsp": "<%@ page language=\"java\" %>\n<main>ok</main>",
                "src/generated.ts": "// generated by tool\nexport const data = [];",
                "src/migrations/seed.ts": "// 자동 생성, 손수정 금지\nexport const seed = [];",
                "src/proto/Chat.java": "// Generated by protocol compiler. DO NOT EDIT!\nclass Chat {}",
                "tests/app.test.ts": "test('x', () => {});",
                "vendor/jquery.js": "window.jQuery = {};",
                "src/main/thirdParty/Client.java": "class Client {}",
                "tmp/helper.py": "print('not shipped')",
            }
            for relative, content in files.items():
                target = repo / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
            subprocess.run(["git", "-C", repo, "add", "."], check=True)

            got = dashboard.source_inventory("fixture", repo)
            self.assertEqual(got["sourceFiles"], 3)
            self.assertEqual(got["totalPhysicalLines"], 9)
            self.assertEqual(got["languageLines"], {
                "Java": 4,
                "TypeScript": 3,
                "JSP": 2,
            })

    def test_grade_requires_ten_percent_analysis_coverage(self):
        self.assertFalse(dashboard.grade_is_representative(142, 538_480))
        self.assertFalse(dashboard.grade_is_representative(1_285, 21_069))
        self.assertTrue(dashboard.grade_is_representative(11_276, 51_507))

    def test_small_js_repo_can_still_be_representative(self):
        self.assertTrue(dashboard.grade_is_representative(75, 75))


if __name__ == "__main__":
    unittest.main()
